[Metadata]
Type = 'gvcs'
Name = 'Gitlab Pages'

[Variables]
MainLang = 'en'
PublishBranch = 'gh-pages'
PublishCommitID='Will be overwritten by publish command sequences'

[FMTVariables]
SourceDir = '{{- .RootDir -}}/.sites'
DestinationDir = '{{- .RootDir -}}/public'
BaseDir = '{{- .RootDir -}}/.sites'
PublishDir = '{{- .RootDir -}}/{{- .PublishBranch -}}'




[[Dependencies]]
Name = 'Hugo'
Condition = 'all-all'
Type = 'command'
Command = 'hugo'

[[Dependencies]]
Name = 'Git'
Condition = 'all-all'
Type = 'command'
Command = 'git'

[[Dependencies]]
Name = 'Bissetii'
Condition = 'all-all'
Type = 'command'
Command = 'bissetii'




[[CMD]]
Name = 'Check Artifact Directory Exists and Ready'
Condition = 'all-all'
Type = 'is-exists'
Location = '{{- .RootDir -}}'
Source = '{{- .DestinationDir -}}/_index.html'

[[CMD]]
Name = 'Remove Git Workspace for Publishing Branch'
Condition = 'all-all'
Type = 'command-quiet'
Location = '{{- .RootDir -}}'
Source = 'git worktree remove "{{- .PublishDir -}}"'

[[CMD]]
Name = 'Delete Publishing Directory Regardlessly'
Condition = 'all-all'
Type = 'delete-recursive-quiet'
Location = '{{- .RootDir -}}'
Source = '{{- .PublishDir -}}'

[[CMD]]
Name = 'Create New Publishing Directory'
Condition = 'all-all'
Type = 'create-path'
Location = '{{- .RootDir -}}'
Source = '{{- .PublishDir -}}'

[[CMD]]
Name = 'Add Git Worktree to Publishing Directory'
Condition = 'all-all'
Type = 'command'
Location = '{{- .RootDir -}}'
Source = 'git worktree add "{{- .PublishDir -}}" "{{- .PublishBranch -}}"'

[[CMD]]
Name = 'Get Publish Branch First Commit for Cleaning'
Condition = 'all-all'
Type = 'command'
Location = '{{- .PublishDir -}}'
Source = 'git rev-list --max-parents=0 --abbrev-commit HEAD'
Save = 'PublishCommitID'

[[CMD]]
Name = 'Clean Up Publishing Directory for Publish Branch'
Condition = 'all-all'
Type = 'command'
Location = '{{- .PublishDir -}}'
Source = 'git reset --hard "{{- .FirstGitCommitID -}}"'

[[CMD]]
Name = 'Remove All Existing Artifacts'
Condition = 'all-all'
Type = 'command'
Location = '{{- .PublishDir -}}'
Source = 'git clean -fd'

[[CMD]]
Name = 'Copy All Publications to Publishing Directory'
Condition = 'all-all'
Type = 'copy-recursive'
Location = '{{- .RootDir -}}'
Source = '{{- .SourceDir -}}'
Target = '{{- .DestinationDir -}}'

[[CMD]]
Name = 'Git Stage All Artifacts into Publishing Directory'
Condition = 'all-all'
Type = 'command'
Location = '{{- .PublishDir -}}'
Source = 'git add .'

[[CMD]]
Name = 'Git Commit All Artifacts into Publishing Directory'
Condition = 'all-all'
Type = 'command'
Location = '{{- .PublishDir -}}'
Source = 'git commit -m "Published as of $(git log "--format=format:%H" -1)"'

[[CMD]]
Name = 'Git Push By Force to Publish Branch'
Condition = 'all-all'
Type = 'command'
Location = '{{- .PublishDir -}}'
Source = 'git push -f origin "{{- .PublishBranch -}}"'

[[CMD]]
Name = 'Remove Git Workspace for Publishing Branch'
Condition = 'all-all'
Type = 'command'
Location = '{{- .RootDir -}}'
Source = 'git worktree remove "{{- .PublishDir -}}"'

[[CMD]]
Name = 'Delete Publishing Directory Regardlessly'
Condition = 'all-all'
Type = 'delete-recursive-quiet'
Location = '{{- .RootDir -}}'
Source = '{{- .PublishDir -}}'
Condition = 'all-all'
