Type = "vertical"
Class = "additional-css-class"
Style = ""
ID = ""
Width = "310px"
Height = "max-content"

[Content]
HTML = """
### Localized CI
Monteur **allows you to run your CI build fully in local system**, enables you
to test your CI before any commit.
"""
AMPHTML = """
### Localized CI
Monteur **allows you to run your CI build fully in local system**, enables you
to test your CI before any commit.
"""

[Thumbnail]
HTML = """
"""
AMPHTML = """
"""
Picture = ""

[Thumbnail.Image]
AltText = "Localized CI"
URL = "/en/locally-builder-310x162.webp"
Width = "310"
Height = "162"
IsMap = ""
LoadingMode = ""
SrcList = """
"""
Layout = ""
Class = ""
Sizes = """
"""
