# creators/authorship list

[bissetii]
"@type" = "Organization"
"name"  = "Monteur Team"
"slogan" = "Assemble with Scale Confidently with Consistency"

[zoralab]
"@type" = "Organization"
"name"  = "ZORALab Team"
"slogan" = "Through Knowledge, We Serve"
