[Metadata]
Name = 'Tar Gunzip'
Description = """
Package application into .tar.gz package file.
"""
Type = 'targz'

[Variables]
ChangelogFrom = 'origin/staging'
ChangelogTo = 'origin/main'

[FMTVariables]
LicensePath = '{{- .RootDir -}}/docs/en/licenses/monteur-software-license.pdf'



[[Dependencies]]
Name = 'Git for Changelog Generation'
Condition = 'all-all'
Type = 'command'
Command = 'git'




[Changelog]
LineBreak = "\n"
Regex = ''

[[Changelog.CMD]]
Name = "Fetch All Local Remote Branches To The Latest"
Type = 'command'
Condition = [ 'all-all' ]
Source = 'git fetch --all'

[[Changelog.CMD]]
Name = "Get Changelog Data from Git Log Between Branches"
Type = 'command'
Condition = [ 'all-all' ]
Source = """git --no-pager log \
"{{- .ChangelogTo -}}..{{- .ChangelogFrom -}}" \
--pretty="format:%h %s"
"""
Save = "ChangelogEntries"




[Packages.001]
OS = [ 'linux' ]
Arch = [ 'amd64' ]
Name = '{{- .PkgName -}}-{{- .PkgVersion -}}-{{- .PkgOS -}}-{{- .PkgArch -}}'
Distribution = [
	'stable',
]
BuildSource = false

[Packages.001.Files]
'{{- .PackageDir -}}/monteur' = '{{- .BuildDir -}}/{{- .PkgOS -}}-{{- .PkgArch -}}'
'{{- .PackageDir -}}/License.pdf' = '{{- .LicensePath -}}'


[Packages.002]
OS = [ 'linux' ]
Arch = [ 'arm64' ]
Name = '{{- .App.ID -}}-{{- .App.Version -}}-{{- .PkgOS -}}-{{- .PkgArch -}}'
Distribution = [
	'stable',
]
BuildSource = false

[Packages.002.Files]
'{{- .PackageDir -}}/monteur' = '{{- .BuildDir -}}/{{- .PkgOS -}}-{{- .PkgArch -}}'
'{{- .PackageDir -}}/License.pdf' = '{{- .LicensePath -}}'


[Packages.003]
OS = [ 'linux' ]
Arch = [ 'arm' ]
Name = '{{- .App.ID -}}-{{- .App.Version -}}-{{- .PkgOS -}}-{{- .PkgArch -}}'
Distribution = [
	'stable',
]
BuildSource = false

[Packages.003.Files]
'{{- .PackageDir -}}/monteur' = '{{- .BuildDir -}}/{{- .PkgOS -}}-{{- .PkgArch -}}'
'{{- .PackageDir -}}/License.pdf' = '{{- .LicensePath -}}'


[Packages.004]
OS = [ 'linux' ]
Arch = [ '386' ]
Name = '{{- .App.ID -}}-{{- .App.Version -}}-{{- .PkgOS -}}-{{- .PkgArch -}}'
Distribution = [
	'stable',
]
BuildSource = false

[Packages.004.Files]
'{{- .PackageDir -}}/monteur' = '{{- .BuildDir -}}/{{- .PkgOS -}}-{{- .PkgArch -}}'
'{{- .PackageDir -}}/License.pdf' = '{{- .LicensePath -}}'


[Packages.005]
OS = [ 'darwin' ]
Arch = [ 'amd64' ]
Name = '{{- .App.ID -}}-{{- .App.Version -}}-{{- .PkgOS -}}-{{- .PkgArch -}}'
Distribution = [
	'stable',
]
BuildSource = false

[Packages.005.Files]
'{{- .PackageDir -}}/monteur' = '{{- .BuildDir -}}/{{- .PkgOS -}}-{{- .PkgArch -}}'
'{{- .PackageDir -}}/License.pdf' = '{{- .LicensePath -}}'


[Packages.006]
OS = [ 'darwin' ]
Arch = [ 'arm64' ]
Name = '{{- .App.ID -}}-{{- .App.Version -}}-{{- .PkgOS -}}-{{- .PkgArch -}}'
Distribution = [
	'stable',
]
BuildSource = false

[Packages.006.Files]
'{{- .PackageDir -}}/monteur' = '{{- .BuildDir -}}/{{- .PkgOS -}}-{{- .PkgArch -}}'
'{{- .PackageDir -}}/License.pdf' = '{{- .LicensePath -}}'




[[CMD]]
Name = 'Placeholder For Any Post CMD Development'
Type = 'placeholder'
Condition = [ 'all-all' ]
Location = ''
Source = ''
Target = ''
