[Metadata]
Name = 'Zip'
Description = """
Package application into .zip package file.
"""
Type = 'zip'




[Variables]
ChangelogFrom = 'origin/staging'
ChangelogTo = 'origin/main'

[FMTVariables]
LicensePath = '{{- .RootDir -}}/docs/en/licenses/monteur-software-license.pdf'




[[Dependencies]]
Name = 'Git for Changelog Generation'
Condition = 'all-all'
Type = 'command'
Command = 'git'




[Packages.001]
Name = '{{- .PkgName -}}-{{- .PkgVersion -}}-{{- .PkgOS -}}-{{- .PkgArch -}}'
OS = [ 'windows' ]
Arch = [ 'amd64' ]
Distribution = [
	'stable',
]
BuildSource = false

[Packages.001.Files]
'{{- .PackageDir -}}/monteur' = '{{- .BuildDir -}}/windows-amd64.exe'
'{{- .PackageDir -}}/License.pdf' = '{{- .LicensePath -}}'

[Packages.002]
Name = '{{- .PkgName -}}-{{- .PkgVersion -}}-{{- .PkgOS -}}-{{- .PkgArch -}}'
OS = [ 'windows' ]
Arch = [ 'arm64' ]
Distribution = [
	'stable',
]
BuildSource = false

[Packages.002.Files]
'{{- .PackageDir -}}/monteur' = '{{- .BuildDir -}}/windows-arm64.exe'
'{{- .PackageDir -}}/License.pdf' = '{{- .LicensePath -}}'




[[CMD]]
Name = 'Placeholder For Any Post CMD Development'
Type = 'placeholder'
Condition = [ 'all-all' ]
Location = ''
Source = ''
Target = ''
