[Metadata]
Name = 'Deep Clean Directory'
Description = """
Deep clean a given directory path.
"""




[Variables]

[FMTVariables]
Path = '{{- .RootDir -}}/path/to/directory'




[[CMD]]
Name = "Remove Path Recursively"
Type = 'delete-recursive-quiet'
Condition = [ 'all-all' ]
Source = '{{- .Path -}}'

[[CMD]]
Name = "Re-Create Path for Restoration"
Type = 'create-path'
Condition = [ 'all-all' ]
Source = '{{- .Path -}}'
