image: debian:latest

stages:
    - test
    - build
    - docs

variables:
    TERM: "xterm"
    GITLAB_CI: "true"

test:
    stage: test
    tags:
        - linux
    environment:
        name: production
    except:
        refs:
            - gh-pages
    coverage: '/total:\s{1,}\(statements\)\s{1,}(\d+.\d+%)/'
    script:
        - echo "pending test"

build:
    stage: build
    tags:
        - linux
    environment:
        name: production
    except:
        refs:
            - gh-pages
    environment:
        name: production
    script:
        - echo "pending build"

compose:
    stage: docs
    tags:
        - linux
    environment:
        name: production
    except:
        refs:
            - gh-pages
    only:
        refs:
            - schedules
    script:
        - echo "pending compose"

pages:
    stage: docs
    tags:
        - linux
    environment:
        name: production
    only:
        refs:
            - gh-pages
    artifacts:
        paths:
            - public
        expire_in: 1 day
    script:
        - mkdir -p public
        - shopt -s extglob
        - mv !(public|.*) public
