Type = "vertical"
Class = "additional-css-class"
Style = ""
ID = ""
Width = "187px"
Height = "max-content"

[Content]
HTML = """
**Aleksandar, Pasaric**
"""
AMPHTML = """
**Aleksandar, Pasaric**
"""

[CTA]
HTML = """
"""
AMPHTML = """
"""

[CTA.Links.1]
URL = "https://www.pexels.com/@apasaric"
HTML = "Pexels"
AMPHTML = "Pexels"
ID = ""
Class = "button clean"
Rel = ""
Download = false
Target = "_blank"

[Thumbnail]
HTML = """
"""
AMPHTML = """
"""
Picture = ""

[Thumbnail.Image]
AltText = "Aleksandar Pasaric"
URL = "/img/monteur/artists/aleksandar-pasaric-560x628.webp"
Width = "187"
Height = "209"
IsMap = ""
LoadingMode = ""
SrcList = """
"""
Layout = ""
Class = ""
Sizes = """
"""
