# Information about the software to be downloaded
[Metadata]
Name = "GolangCI-Lint"
Description = """
Go communities CI linter
"""
Type = "https-download"




# Customization
[Variables]
Version = "1.43.0"
BaseURL = "https://github.com/golangci/golangci-lint/releases/download"




# Supported OS and CPU Architectures program sources. The Key for supported
# OS and CPU complies to the format:
#	[Sources.{GOOS}-{GOARCH}]
# Only list out supported packages will do.
[Sources.darwin-amd64]
Format = "tar.gz"
Archive = "golangci-lint-{{- .Version -}}-{{ .ComputeSystem }}.{{- .Format -}}"
URL = "{{- .BaseURL -}}/v{{- .Version -}}/{{- .Archive -}}"

[Sources.darwin-arm64]
Format = "tar.gz"
Archive = "golangci-lint-{{- .Version -}}-{{ .ComputeSystem }}.{{- .Format -}}"
URL = "{{- .BaseURL -}}/v{{- .Version -}}/{{- .Archive -}}"

[Sources.freebsd-386]
Format = "tar.gz"
Archive = "golangci-lint-{{- .Version -}}-{{ .ComputeSystem }}.{{- .Format -}}"
URL = "{{- .BaseURL -}}/v{{- .Version -}}/{{- .Archive -}}"

[Sources.freebsd-amd64]
Format = "tar.gz"
Archive = "golangci-lint-{{- .Version -}}-{{ .ComputeSystem }}.{{- .Format -}}"
URL = "{{- .BaseURL -}}/v{{- .Version -}}/{{- .Archive -}}"

[Sources.freebsd-armv6]
Format = "tar.gz"
Archive = "golangci-lint-{{- .Version -}}-{{ .ComputeSystem }}.{{- .Format -}}"
URL = "{{- .BaseURL -}}/v{{- .Version -}}/{{- .Archive -}}"

[Sources.freebsd-armv7]
Format = "tar.gz"
Archive = "golangci-lint-{{- .Version -}}-{{ .ComputeSystem }}.{{- .Format -}}"
URL = "{{- .BaseURL -}}/v{{- .Version -}}/{{- .Archive -}}"

[Sources.linux-386]
Format = "tar.gz"
Archive = "golangci-lint-{{- .Version -}}-{{ .ComputeSystem }}.{{- .Format -}}"
URL = "{{- .BaseURL -}}/v{{- .Version -}}/{{- .Archive -}}"

[Sources.linux-amd64]
Format = "tar.gz"
Archive = "golangci-lint-{{- .Version -}}-{{ .ComputeSystem }}.{{- .Format -}}"
URL = "{{- .BaseURL -}}/v{{- .Version -}}/{{- .Archive -}}"

[Sources.linux-arm64]
Format = "tar.gz"
Archive = "golangci-lint-{{- .Version -}}-{{ .ComputeSystem }}.{{- .Format -}}"
URL = "{{- .BaseURL -}}/v{{- .Version -}}/{{- .Archive -}}"

[Sources.linux-armv6]
Format = "tar.gz"
Archive = "golangci-lint-{{- .Version -}}-{{ .ComputeSystem }}.{{- .Format -}}"
URL = "{{- .BaseURL -}}/v{{- .Version -}}/{{- .Archive -}}"

[Sources.linux-armv7]
Format = "tar.gz"
Archive = "golangci-lint-{{- .Version -}}-{{ .ComputeSystem }}.{{- .Format -}}"
URL = "{{- .BaseURL -}}/v{{- .Version -}}/{{- .Archive -}}"

[Sources.linux-misps64]
Format = "tar.gz"
Archive = "golangci-lint-{{- .Version -}}-{{ .ComputeSystem }}.{{- .Format -}}"
URL = "{{- .BaseURL -}}/v{{- .Version -}}/{{- .Archive -}}"

[Sources.linux-misps64le]
Format = "tar.gz"
Archive = "golangci-lint-{{- .Version -}}-{{ .ComputeSystem }}.{{- .Format -}}"
URL = "{{- .BaseURL -}}/v{{- .Version -}}/{{- .Archive -}}"

[Sources.linux-ppc64le]
Format = "tar.gz"
Archive = "golangci-lint-{{- .Version -}}-{{ .ComputeSystem }}.{{- .Format -}}"
URL = "{{- .BaseURL -}}/v{{- .Version -}}/{{- .Archive -}}"

[Sources.linux-riscv64]
Format = "tar.gz"
Archive = "golangci-lint-{{- .Version -}}-{{ .ComputeSystem }}.{{- .Format -}}"
URL = "{{- .BaseURL -}}/v{{- .Version -}}/{{- .Archive -}}"

[Sources.linux-s390x]
Format = "tar.gz"
Archive = "golangci-lint-{{- .Version -}}-{{ .ComputeSystem }}.{{- .Format -}}"
URL = "{{- .BaseURL -}}/v{{- .Version -}}/{{- .Archive -}}"

[Sources.windows-amd64]
Format = "tar.gz"
Archive = "golangci-lint-{{- .Version -}}-{{ .ComputeSystem }}.{{- .Format -}}"
URL = "{{- .BaseURL -}}/v{{- .Version -}}/{{- .Archive -}}"

[Sources.windows-arm64]
Format = "tar.gz"
Archive = "golangci-lint-{{- .Version -}}-{{ .ComputeSystem }}.{{- .Format -}}"
URL = "{{- .BaseURL -}}/v{{- .Version -}}/{{- .Archive -}}"

[Sources.windows-armv6]
Format = "tar.gz"
Archive = "golangci-lint-{{- .Version -}}-{{ .ComputeSystem }}.{{- .Format -}}"
URL = "{{- .BaseURL -}}/v{{- .Version -}}/{{- .Archive -}}"

[Sources.windows-armv7]
Format = "tar.gz"
Archive = "golangci-lint-{{- .Version -}}-{{ .ComputeSystem }}.{{- .Format -}}"
URL = "{{- .BaseURL -}}/v{{- .Version -}}/{{- .Archive -}}"




# Setup the unpacked software directories/files into the local bin directory.
#
# NOTE: The key field is mainly for sorting purposes.
[[Setup]]
Type = "move"
Condition = "all-all"
Source = "golangci-lint-{{- .Version -}}-{{ .ComputeSystem }}/golangci-lint"
Target = "golangci-lint"




# Config file for localized filesystem initialization.
[Config]
linux = """
#!/bin/bash
case $1 in
--stop)
	;;
*)
	if [ ! -z "$(type -p golangci-lint)" ]; then
		1>&2 printf "[ DONE  ] golangci-lint is available.\\n"
	else
		1>&2 printf "[ ERROR ] golangci-lint is missing.\\n"
		stop_go
	fi
	;;
esac
"""
