[Metadata]
Name = "GolangCI-Lint"
Version = "v3.0.0"
URL = "/ci-jobs/setup/golangci-lint/golangci-lint-v3p0p0.toml"
Language = "en"




[[MinRequirements]]
Content = "Montuer version: <b><code>v0.0.3</code> and above</b>."

[[MinRequirements]]
Content = """
Supported platform: <b>STRICTLY depends on <code>Monteur</code>
availability</b>.
"""




[[Installations]]
Content = """
Download and place the recipe file into your
<code>.configs/monteur/setup/jobs/</code> directory as
<code>golangci-lint.toml</code>.
"""

[[Installations]]
Content = """
Update the recipe's <code>Variables.Version</code> matching the new version
number.
"""

[[Installations]]
Content = """
Update the recipe's <code>Variables.BaseURL</code> if the core development team
changes it again.
"""

[[Installations]]
Content = """
Update the recipe's <code>Sources.XXX.Checksum.Value</code> with each matching
checksum values for matching new release.
"""




[[Changelog]]
BackwardCompatible = false
Content = """
Refactored for <code>arm</code> development environment like using
<code>.SourceSystem</code> instead of <code>.ComputeSystem</code> in CEU.
"""
