[Metadata]
Name = "GolangCI-Lint"
Version = "v1.0.0"
URL = "/ci-jobs/setup/golangci-lint/golangci-lint-v1p0p0.toml"
Language = "en"




[[MinRequirements]]
Content = "Montuer version: <b><code>v0.0.1</code></b>."

[[MinRequirements]]
Content = """
Supported platform: <b>STRICTLY depends on <code>Monteur</code>
availability</b>.
"""




[[Installations]]
Content = """
Download and place the recipe file into your
<code>.configs/monteur/setup/programs/</code> directory as
<code>golangci-lint.toml</code>.
"""

[[Installations]]
Content = """
Update the recipe's <code>Variables.Version</code> matching the new version
number.
"""

[[Installations]]
Content = """
Update the recipe's <code>Variables.BaseURL</code> if the core development team
changes it again.
"""

[[Installations]]
Content = """
Update the recipe's <code>Sources.XXX.Checksum.Value</code> with each matching
checksum values for matching new release.
"""




[[Changelog]]
BackwardCompatible = true
Content = "Created the base TOML configuration recipe."

[[Changelog]]
BackwardCompatible = true
Content = "Tested with GitLab CI."

[[Changelog]]
BackwardCompatible = true
Content = "Updated to GolangCI-Lint version <code>1.43.0</code>."
