[Filesystem]
BaseDir = "pkg/"
WorkingDir = ".monteurFS/tmp/"
BuildDir = ".monteurFS/build/"
ScriptDir = ".scripts/"
BinDir = ".monteurFS/bin/"
BinCfgDir = ".monteurFS/config"
DocDir = "docs/"
SecretsDir = [
	"{{ .HomeDir }}/.secrets",
	"{{ .RootDir }}/.configs/monteur/secrets",
]

[Language]
Name = "English"
AlternateName = "en"
