[Filesystem]
BaseDir = "pkg/"
WorkingDir = "tmp/"
BuildDir = "build/"
ScriptDir = ".scripts/"
BinDir = ".bin/"
BinCfgDir = "./.bin/config.d/"
DocDir = "public/"
SecretsDir = [
	"{{ .HomeDir }}/.secrets",
	"{{ .RootDir }}/.configs/monteur/secrets",
]

[Language]
Name = "English"
AlternateName = "en"
