[Filesystem]
BaseDir = "pkg/"
WorkingDir = "tmp/"
BuildDir = "build/"
ScriptDir = ".scripts/"
BinDir = ".bin/"
BinCfgDir = "./.bin/config.d/"
DocDir = "public/"

[Language]
Name = "English"
AlternateName = "en"
