[Filesystem]
BaseDir = 'gopkg/'
WorkingDir = '.monteurFS/tmp/'
BuildDir = '.monteurFS/build/'
ScriptDir = '.scripts/'
BinDir = '.monteurFS/bin/'
BinCfgDir = '.monteurFS/config'
LogDir = '.monteurFS/log'
DataDir = '{{- .RootDir -}}/.configs/monteur/data'
SecretsDir = [
	'{{ .HomeDir }}/.secrets',
	'{{ .RootDir }}/.configs/monteur/secrets',
]

[Language]
Name = 'English'
Code = 'en'

[Variables]
Placeholder = 'en'

[FMTVariables]
FMTPlaceholer = 'Language: "{{- .Placeholder -}}"'
