[Title]
HTML = "<p>Monteur</p>"
AMPHTML = "<p>Monteur</p>"


[Menu]
HTML = ""
AMPHTML = ""


[Close]
HTML = ""
AMPHTML = ""


[Submenu]
HTML = ""
AMPHTML = ""


[Logo]
HTML = ""
AMPHTML = ""
URL = "/img/logo/zoralab-monteur-1200x1200.svg"
Width = "200"
Height = "200"
AltText = ""
Class = ""
