[DEB]
Compat = 9
Source = '3.0 (native)'

[DEB.Control]
Standards = '3.9.8'
Section = 'devel'
Priority = 'optional'

[DEB.Depends]
Build = [
	'debhelper (>=9)',
]
Dependencies = [
	'${misc:Depends}',
]

[DEB.Copyrights]
Format = 'http://www.debian.org/doc/packaging-manuals/copyright-format/1.0/'

[DEB.Executions]
Rules = """
#!/usr/bin/make -f

# Uncomment this to turn on verbose mode.
#export DH_VERBOSE=1

%:
	dh $@

override_dh_auto_build:
	echo "nothing to override"
"""
Install = [
	"monteur usr/share/monteur/bin",
]
