[Metadata]
Type = 'static-site-generator'
Name = 'GoHugo'

[Variables]
MainLang = 'en'
PublishBranch = 'gh-pages'
PublishCommitID='Will be overwritten by publish command sequences'

[FMTVariables]
SourceDir = '{{- .RootDir -}}/.sites'
DestinationDir = '{{- .WorkingDir -}}/public'
PublishDir = '{{- .WorkingDir -}}/{{- .PublishBranch -}}'




[[Dependencies]]
Name = 'Hugo'
Condition = 'all-all'
Type = 'command'
Command = 'hugo'

[[Dependencies]]
Name = 'Git'
Condition = 'all-all'
Type = 'command'
Command = 'git'

[[Dependencies]]
Name = 'Bissetii'
Condition = 'all-all'
Type = 'command'
Command = 'bissetii'




[[CMD]]
Name = "Hugo Build with Minimifaction"
Type = 'command'
Condition = 'all-all'
Location = '{{- .SourceDir -}}'
Source = 'hugo --minify --destination "{{- .DestinationDir -}}"'

[[CMD]]
Name = "Hugo Workaround with 404"
Type = 'copy'
Condition = 'all-all'
Location = '{{- .SourceDir -}}'
Source = '{{- .DestinationDir -}}/{{- .MainLang -}}/404.html'
Target = '{{- .DestinationDir -}}/404.html'
