[Metadata]
Name = 'Monteur'
ID = 'monteur'
Type = 'app'
Command = 'monteur'
Summary = 'A software manufacturing automation and assembling tools in one app'
Description = """
Monteur focuses on keeping the software development repository's continuous
improvements execution seamlessly scalable with great consistency.

Das Monteur - Getting the job done locally and remotely at scale!
"""


[[Metadata.Maintainers]]
Name = 'ZORALab Enterprise'
Email = 'tech@zoralab.com'
