[Metadata]
Name = 'DEB'
Description = """
Package monteur into .deb package file using manual commands.
"""
Type = 'deb-manual'

[Variables]
GPGID = 'hello@zoralab.com'
GPGExistence = ''  # to be filled later for verifications

[FMTVariables]
Lintian = '{{- .DataDir -}}/deb/lintian'
Profile = '{{- .DataDir -}}/deb/profiles'




[[Dependencies]]
Name = 'DEB Builder'
Condition = 'all-all'
Type = 'command'
Command = 'debuild'

[[Dependencies]]
Name = 'GPG Tool'
Condition = 'all-all'
Type = 'command'
Command = 'gpg'




[Package.001]
OS = [ 'linux' ]
CPU = [ 'amd64' ]
Departure = '{{- .BuildDir -}}'
Arrival = '{{- .WorkingDir -}}/linux-amd64'
Subjects = [ '{{- .BuildDir -}}/linux-amd64' ]

[Package.002]
OS = [ 'linux' ]
CPU = [ 'arm64' ]
Departure = '{{- .BuildDir -}}'
Arrival = '{{- .WorkingDir -}}/linux-amd64'
Subjects = [ '{{- .BuildDir -}}/linux-arm64' ]




[[CMD]]
Name = "Get GPG Secret Key for Verifications"
Type = 'command'
Condition = [ 'all-all' ]
Source = 'gpg --list-secret-keys "{{- .GPGID }}"'
Save = 'GPGExistence'

[[CMD]]
Name = "Verify GPG Secret Key Must Exists For Signing"
Type = 'is-not-empty'
Condition = [ 'all-all' ]
Source = '{{- GPGExistence -}}'

[[CMD]]
Name = "Compile Deb Package"
Type = 'command'
Condition = [ 'all-all' ]
Location = '{{- .Arrival -}}'
Source = """debuild -k{{- .GPGID }} -S \
--include-dir {{ .Lintian }} \
--profile {{ .Profile }}"""
