[Metadata]
Name = 'DEB'
Description = """
Package monteur into .deb package file.
"""
Type = 'deb'

[Variables]

[FMTVariables]




[[Dependencies]]
Name = 'Go'
Condition = 'all-all'
Type = 'command'
Command = 'go'




[Package.linux-amd64]
Source = '{{- .BuildDir -}}/linux-amd64'
OS = 'linux'
CPU = 'amd64'

[Package.linux-arm64]
Source = '{{- .BuildDir -}}/linux-arm64'
OS = 'linux'
CPU = 'arm64'




[[CMD]]
Name = "Placeholder"
Type = 'command'
Condition = [ 'all-all' ]
Source = 'echo "just a command placeholder"'
