[Metadata]
Name = "Debuild"
Version = "v2.0.0"
URL = "/ci-jobs/package/debuild/debuild-v2p0p0.toml"
Language = "en"




[[MinRequirements]]
Content = "Montuer version: <b><code>v0.0.2</code> and above</b>."

[[MinRequirements]]
Content = """
Supported platform: <b>STRICTLY depends on <code>Monteur</code>
availability</b>.
"""




[[Installations]]
Content = """
Download and place the recipe file into your
<code>.configs/monteur/package/jobs/</code> directory as
<code>debuild.toml</code>.
"""

[[Installations]]
Content = """
Update the recipe's <code>Variables.GPGID</code> pointing to your GPG signing
key.
"""

[[Installations]]
Content = """
Update the recipe's <code>Packages.XXX</code> and list all the packages.
Duplicate if there are more build variants.
"""

[[Installations]]
Content = """
Update the recipe's <code>Packages.XXX.OS</code> list all supported operating
system. <b>Minimum 1</b>.
"""

[[Installations]]
Content = """
Update the recipe's <code>Packages.XXX.Arch</code> list all supported CPU
architecture. <b>Minimum 1</b>.
"""

[[Installations]]
Content = """
Update the recipe's <code>Packages.XXX.Changelog</code> pointing to the
package's corresponding filepath.
"""

[[Installations]]
Content = """
Update the recipe's <code>Packages.XXX.Name</code> filename without file
extension.
"""

[[Installations]]
Content = """
Update the recipe's <code>Packages.XXX.Distribution</code> list of supported
distributions.
"""

[[Installations]]
Content = """
Update the recipe's <code>Packages.XXX.BuildSource</code> instructs Monteur to
build as source code package, not binary one, and not both. If both are
required, use a separate recipe file.
"""

[[Installations]]
Content = """
Update the recipe's <code>Packages.XXX.Files</code> assemble the list of file
for the package.
"""




[[Changelog]]
BackwardCompatible = false
Content = """
Removed <code>[Changelog]</code> as Monteur <code>v0.0.2</code> supplies
dedicated Prepare CI Job for this specific role."
"""

[[Changelog]]
BackwardCompatible = true
Content = """
Abstracted as many <code>FMTVariables</code> to many packages fields instead of
hardcoding to specific ones.
"""
