[Metadata]
Name = 'Debuild'
Description = """
Package application into .deb package file using manual commands.
"""
Type = 'deb-manual'

[Variables]
ChangelogFrom = 'origin/staging'
ChangelogTo = 'origin/main'
GPGID = 'name@email.com'
GPGExistence = ''  # to be filled by [CMD]

[FMTVariables]




[[Dependencies]]
Name = 'DEB Builder'
Condition = 'all-all'
Type = 'command'
Command = 'debuild'

[[Dependencies]]
Name = 'GPG Tool'
Condition = 'all-all'
Type = 'command'
Command = 'gpg'

[[Dependencies]]
Name = 'Git for Changelog Generation'
Condition = 'all-all'
Type = 'command'
Command = 'git'




[Changelog]
LineBreak = "\n"
Regex = ''

[[Changelog.CMD]]
Name = "Get Changelog Data from Git Log Between Branches"
Type = 'command'
Condition = [ 'all-all' ]
Source = """git --no-pager log \
"{{- .ChangelogTo -}}..{{- .ChangelogFrom -}}" \
--pretty="format:%h %s"
"""
Save = "ChangelogEntries"




[Packages.001]
OS = [ 'linux' ]
Arch = [ 'amd64' ]
Changelog = '{{- .DataDir -}}/debian/changelog-amd64'
Distribution = [
	'stable',
]
BuildSource = false

[Packages.001.Files]
'{{- .PackageDir -}}/monteur' = '{{- .BuildDir -}}/linux-amd64'




[[CMD]]
Name = "Get GPG Secret Key for Verifications"
Type = 'command'
Condition = [ 'all-all' ]
Source = 'gpg --list-secret-keys "{{- .GPGID }}"'
Save = 'GPGExistence'

[[CMD]]
Name = "Verify GPG Secret Key Must Exists For Signing"
Type = 'is-not-empty'
Condition = [ 'all-all' ]
Source = '{{- .GPGExistence -}}'

[[CMD]]
Name = "Compile Deb Package with Debuild"
Type = 'command'
Condition = [ 'all-all' ]
Location = '{{- .PackageDir -}}'
Source = 'debuild -b -k{{- .GPGID }} -a{{- index .PkgArch 0 }}'
