[Metadata]
Name = 'Hugo'
Description = """
Using Hugo static site generator to compose Monteur's web documentations
artifacts.
"""




[Variables]
MainLang = 'en'
PublishBranch = 'gh-pages'
PublishCommitID='Will be overwritten by publish command sequences'




[FMTVariables]
SourceDir = '{{- .RootDir -}}/.sites'
DestinationDir = '{{- .WorkingDir -}}/public'
PublishDir = '{{- .WorkingDir -}}/{{- .PublishBranch -}}'




[[Dependencies]]
Name = 'Hugo'
Condition = 'all-all'
Type = 'command'
Command = 'hugo'

[[Dependencies]]
Name = 'Git'
Condition = 'all-all'
Type = 'command'
Command = 'git'




[[CMD]]
Name = "Hugo Build with Minimifaction"
Type = 'command'
Condition = [ 'all-all' ]
Location = '{{- .SourceDir -}}'
Source = 'hugo --minify --destination "{{- .DestinationDir -}}"'

[[CMD]]
Name = "Hugo Workaround with 404"
Type = 'copy'
Condition = [ 'all-all' ]
Location = '{{- .SourceDir -}}'
Source = '{{- .DestinationDir -}}/{{- .MainLang -}}/404.html'
Target = '{{- .DestinationDir -}}/404.html'

[[CMD]]
Name = "Copy GitLab CI if available"
Type = 'copy-quiet'
Condition = [ 'all-all' ]
Source = '{{- .RootDir -}}/.gitlab-ci.yml'
Target = '{{- .DestinationDir -}}/.gitlab-ci.yml'
